// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = (function() {
    function _Class(arg) {
      this.d = arg.d, this.w = arg.w;
      if (this.w == null) {
        this.w = window;
      }
      if (this.d == null) {
        this.d = document;
      }
      this.resolves = [];
      this.isReady = false;
      this.YT = null;
    }

    _Class.prototype.load = function() {
      var firstScriptTag, tag;
      this.w.onYouTubeIframeAPIReady = (function(_this) {
        return function() {
          var i, len, ref, resolve, results;
          _this.YT = _this.w.YT;
          _this.isReady = true;
          ref = _this.resolves;
          results = [];
          for (i = 0, len = ref.length; i < len; i++) {
            resolve = ref[i];
            results.push(resolve(_this.YT));
          }
          return results;
        };
      })(this);
      tag = this.d.createElement("script");
      tag.src = "https://www.youtube.com/iframe_api";
      firstScriptTag = (this.d.getElementsByTagName("script"))[0];
      return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    };

    _Class.prototype.ready = function() {
      if (this.isReady) {
        return resolve(this.YT);
      } else {
        return this.resolves.push(resolve);
      }
    };

    return _Class;

  })();

}).call(this);
